servers:
  creative:
    host: slabserver.org
    port: 26565
  survival:
    host: slabserver.org
    port: 25565
  nexus:
    host: slabserver.org
    port: 27565
  relay:
    host: r1.slabserver.org
    port: 25565