name: SimpleServerSender
version: 1.0.0
main: org.slabserver.plugin.SimpleServerSender
api-version: 1.20

commands:
  creative:
    description: Transfer to the Creative server
    usage: /creative
    permission: transfer.creative
  survival:
    description: Transfer to the Survival server
    usage: /survival
    permission: transfer.survival
  nexus:
    description: Transfer to the Nexus server
    usage: /nexus
    permission: transfer.nexus
  relay:
    description: Transfer to the Survival server via Relay
    usage: /relay
    permission: transfer.relay

permissions:
  transfer.creative:
    description: Allows use of /creative
    default: true
  transfer.survival:
    description: Allows use of /survival
    default: true
  transfer.nexus:
    description: Allows use of /nexus
    default: true
  transfer.relay:
    description: Allows use of /relay
    default: true